project:
  type: website
  output-dir: docs

website:
  title: "R4DS-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true
    comments: 
      hypothesis: true

editor: visual

