project:
  type: website

website:
  title: "R4DS-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css
    toc: true

editor: visual

